CREATE TABLE "POLICY_TBL_CTRL_BY_ROW"
(
"CTRL_BY_ROW_ID" NUMBER NOT NULL ENABLE,
"SCHEMA_NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE,
"TABLE_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
"COLUMN_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
"VALUE" VARCHAR2(2000 CHAR),
"FILTER_OPERATOR" VARCHAR2(20 CHAR) DEFAULT 'EQUAL' NOT NULL, ENABLE,
"DESCRIPTION" VARCHAR2(500 CHAR),
CONSTRAINT "POLICY_TBL_CTRL_BY_ROW_PK" PRIMARY KEY ("CTRL_BY_ROW_ID")
);
/
CREATE TABLE "POLICY_TBL_CTRL_BY_COL"
(
"CTRL_BY_COL_ID" NUMBER NOT NULL ENABLE,
"SCHEMA_NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE,
"TABLE_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,
"COLUMN_NANE" VARCHAR2(100 CHAR) NOT NULL ENABLE,
"MASK_ALGO" VARCHAR2(2000 CHAR) DEFAULT 'LAST_4_DIGIT' NOT NULL ENABLE,
"DESCRIPTION" VARCHAR2(500 CHAR), CONSTRAINT
"POLICY_TBL_CTRL_BY_COL_PK" PRIMARY KEY ("CTRL_BY_COL_ID")
);
/
CREATE TABLE "POLICY"
( "POLICY_ID NUMBER NOT NULL, ENABLE,
"POLICY_NAME" VARCHAR2(100 CHAR) NOT NULL' ENABLE,
"DEFINITION" VARCHAR2(500 CHAR),
"POLICY_TYPE" VARCHAR2(100 CHAR) DEFAULT,
CONSTRAINT "POLICY_PK" PRIMARY KEY ("POLICY_ID"),
CONSTRAINT "POLICY_UK" UNIQUE ("POLICY_NAME");
/
CREATE TABLE "POLICY_GROUP"
("POLICY_GROUP_ID" NUMBER NOT NULL ENABLE,
"POLICY_GROUP_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE,.
"DEFINITION" VARCHAR2(500 CHAR),
"GROUP_TYPE" VARCHAR2(100 CHAR) DEFAULT 'PERSONA' NOT NULL ENABLE,
CONSTRAINT "POLICY_GROUP_PK" PRIMARY KEY ("POLICY_GROUP_ID")
);
/

CREATE TABLE "CTRL_BY_ROW_IN_POLICY"
("CTRL_BY_ROW_ID" NUMBER NOT NULL ENABLE,
"POLICY_ID" NUMBER NOT NULL ENABLE,
"STATUS" VARCHAR2(20 BYTE) DEFAULT 'ACTIVE' NOT NULL ENABLE,
CONSTRAINT "CTL_BY_ROW_IN_POLICY_PK" PRIMARY KEY ("CTRL_BY_ROW_ID", "POLICY_ID"),
CONSTRAINT "FK_CTRL_BY_ROW" FOREIGN KEY ("CTRL_BY_ROW_ID") REFERENCES "TBL_CTRL_BY_ROW" ("CTRL_BY_ROW_ID"') ENABLE,
CONSTRAINT "FK_POLICY_ROW" FOREIGN KEY ("POLICY_ID") REFERENCES "POLICY" ("POLICY_ID") ENABLE
);
/
CREATE TABLE "CTRL_BY_COL_IN_POLICY"
("CTRL_BY_COL_ID" NUMBER NOT NULL ENABLE,
"POLICY_ID" NUMBER NOT NULL ENABLE,
"STATUS" VARCHAR2(20 BYTE) DEFAULT 'ACTIVE' NOT NULL ENABLE,
CONSTRAINT "PK_CTL_BY_COL_IN_POLICY" PRIMARY KEY ("CTRL_BY_COL_ID", "POLICY_ID"),
CONSTRAINT "FK_CTL_BY_COL" FOREIGN KEY ("CTRL_BY_COL_ID") REFERENCES "TBL_CTRL_BY_COL" ("CTRL_BY_COL_ID") ENABLE,
CONSTRAINT "FK_COL_IN_POLICY" FOREIGN KEY ("POLICY_ID") REFERENCES "POLICY" ("POLICY_ID") ENABLE
);
/
CREATE TABLE "ENTITLEMENT"
("USER_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE,
"POLICY_GROUP_ID" NUMBER NOT NULL ENABLE,
"STATUS". VARCHAR2(10 BYTE) DEFAULT 'ACTIVE',
"DATE_ENTITLED" DATE,
"DATE_REVOKED" DATE,
CONSTRAINT "PK_ENTITLEMENT" PRIMARY KEY ("USER_ID", "POLICY_GROUP_ID"),
CONSTRAINT "FK_ENTITLEMENT" FOREIGN KEY ("POLICY_GROUP_ID") REFERENCES "POLICY_GROUP" ("POLICY_GROUP_ID") ENABLE
);
/